name: Check lint failure

on:
  pull_request:
    types:
      - opened
#    branches:
#      - $default-branch

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  comment_on_lint_failure:
    name: Comment on lint failure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn
      - name: Install
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn build
      - name: lint
        run: yarn lint
      - name: Check dependency versions
        run: node scripts/check-dependencies.js
      - name: Install website
        working-directory: docs/
        run: yarn
      - name: Lint website
        working-directory: docs/
        run: yarn lint
      - name: Save PR number
        if: ${{ failure() }}
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR
      - uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: pr-number
          path: pr/NR
