name: Testing Github Action

on:
  pull_request:
    paths:
      - '**'
      - '.github/workflows/testing-action.yaml'
  workflow_dispatch:

jobs:
  Build-Container-dev:
    uses: celo-org/reusable-workflows/.github/workflows/container-cicd.yaml@v1.14.2
    if: github.ref != 'refs/heads/main'
    with:
      workload-id-provider: projects/1094498259535/locations/global/workloadIdentityPools/gh-patrick-testing/providers/github-by-repos
      service-account: patrick-testing-ro@security-circle.iam.gserviceaccount.com
      artifact-registry: ${{ vars.DEV_IMAGE_REPO }}/testing-action
      tags: testing
      context: ./
      trivy: false


