name: Testing Github Action

on:
  pull_request:
    paths:
      - 'testing-action/**'
      - '.github/workflows/testing-action.yaml'
  push:
    paths:
      - 'testing-action/**'
      - '.github/workflows/testing-action.yaml'
  workflow_dispatch:

jobs:
  release:
    runs-on: [linux]
    permissions:
      contents: write
      id-token: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Fetch dynamic secrets from Akeyless
        id: fetch-dynamic-secrets
        uses: akeyless-community/akeyless-github-action@v1.0.1
        with:
          access-id: p-kf9vjzruht6l
          dynamic-secrets: |
            - name: "/dynamic-secrets/keys/github/docs/contents=write,pull_requests=write"
              output-name: "NPM_TOKEN"
          access-type: jwt

  Build-Container-dev:
    uses: celo-org/reusable-workflows/.github/workflows/container-cicd.yaml@v1.14.2
    if: github.ref != 'refs/heads/main'
    with:
      workload-id-provider: ${{ vars.WORKLOAD_ID_PROVIDER_NON_MAIN }}
      service-account: patrick-testing-ro@clabs-secrets-and-permissions.iam.gserviceaccount.com
      artifact-registry: ${{ vars.DEV_IMAGE_REPO }}/testing-action
      tags: testing
      context: ./testing-action
      trivy: false
