---
name: 'test repo dispatch'

on:
  repository_dispatch:
    types: [teamchange]
jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    permissions:
      contents: write
      id-token: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Try to fail
        run: exit 1

