---
name: 'test repo dispatch'

on:
  repository_dispatch:
#    types: [membership, team.edited, team_add, team.added_to_repository]
jobs:
  release:
    name: Release
    permissions:
      contents: write
      id-token: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4


