---
name: 'test repo dispatch'

on:
  repository_dispatch:
    types: [team, team_add]

jobs:
  release:
    name: Release
    runs-on: ['ubuntu']
    permissions:
      contents: write
      id-token: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Akeyless Get Secrets
        id: get_auth_token
        uses:
          docker://us-west1-docker.pkg.dev/devopsre/akeyless-public/akeyless-action:latest
        with:
          api-url: https://api.gateway.akeyless.celo-networks-dev.org
          access-id: p-kf9vjzruht6l
          static-secrets: '{"/static-secrets/test-fail":"NPM_TOKEN"}'

